# Generated by Django 2.0 on 2020-05-15 15:24

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(blank=True, max_length=100, null=True)),
                ('poster1', models.ImageField(upload_to=videos.models.upload_poster1)),
                ('link', models.URLField(blank=True)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField()),
                ('produced_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=100, null=True)),
                ('poster', models.ImageField(upload_to=videos.models.upload_poster)),
                ('link', models.URLField(blank=True)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('size', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
