# Generated by Django 3.0.3 on 2020-02-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('movie', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=60)),
                ('singer', models.CharField(max_length=50)),
                ('music', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=80)),
                ('download', models.URLField()),
            ],
        ),
    ]
