# Generated by Django 2.0 on 2020-04-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20200417_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='singer',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='movie',
        ),
    ]
